// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

///连接到打印机
Future<Printer> connectToPrinter(
        {required int vendorId, required int productId}) =>
    RustLib.instance.api.crateApiPrinterConnectToPrinter(
        vendorId: vendorId, productId: productId);

///打印简单的文本
Future<void> printerSimpleText(
        {required Printer printer, required String text}) =>
    RustLib.instance.api
        .crateApiPrinterPrinterSimpleText(printer: printer, text: text);

///打印原始数据
Future<void> printerRawData(
        {required Printer printer, required List<int> rawData}) =>
    RustLib.instance.api
        .crateApiPrinterPrinterRawData(printer: printer, rawData: rawData);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Printer>>
abstract class Printer implements RustOpaqueInterface {}
